- name: Check the image directory
  ansible.builtin.file:
    path: "{{ image_dir }}/{{ image_subdir }}"
    state: directory
    mode: '0755'

- name: Download image or check file exists
  ansible.builtin.get_url:
    url: "{{ download.url }}"
    dest: "{{ image_dir }}/{{ image_subdir }}/{{ download.filename }}"
    checksum: "{{ download.checksum }}"
    mode: "0644"

- name: Create the golden image
  community.general.proxmox_kvm:
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    api_host: '{{ inventory_hostname }}'
    node: '{{ proxmox_node }}'
    name: '{{ golden_image.name }}'
    vmid: "{{ base_vmid | int + play_hosts.index(inventory_hostname) }}"
    scsi:
      scsi0: 'local-lvm:0,import-from=local:{{ image_subdir }}/{{ download.filename }},discard=on,ssd=1'
    ostype: 'l26'
    machine: 'q35'
    cpu: 'host'
    balloon: 0
    scsihw: virtio-scsi-pci
    boot: order=scsi0
    net: '{"net0":"virtio,bridge=vmbr0"}'
    serial: '{"serial0":"socket"}'
    sockets: 1
    ide:
      ide2: 'local-lvm:cloudinit'
    vga: serial0
    agent: 'enabled=1'
    template: true
