alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

#kubeControllerManager:
#  enabled: false
#
#kubeEtcd:
#  enabled: false
#
#kubeProxy:
#  enabled: false
#
#kubeScheduler:
#  enabled: false
