- name: Lookup the template
  community.general.proxmox_vm_info:
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_host: "{{ inventory_hostname }}"
    node: "{{ proxmox_node }}"
    name: "{{ vm.template }}"
  register: vm_info

- name: Generate VMIDs for this host
  set_fact:
    node_base_vmid: "{{ base_vmid | int + vm.count * play_hosts.index(inventory_hostname) }}"

- name: Append hosts to global list
  set_fact:
    vm_hosts: "{{ vm_hosts | default([]) + [ vm.name ~ ((node_base_vmid | int + item | int) | string) ] }}"
  loop: "{{ range(0, vm.count) | list }}"

- name: Upload Cloud-Init data
  ansible.builtin.template:
    src: user-data.j2
    dest: '{{ snippets_dir }}/{{ vm.name }}{{ node_base_vmid | int + item }}-user-data.yml'
    owner: root
    group: root
    mode: "0644"
  loop: "{{ range(0, vm.count) | list }}"

- name: Clone VM
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_host: "{{ inventory_hostname }}"
    node: "{{ proxmox_node }}"
    clone: "dummy"
    vmid: "{{ vm_info.proxmox_vms[0].vmid }}"
    newid: "{{ node_base_vmid | int + item }}"
    name: "{{ vm.name }}{{ node_base_vmid | int + item }}"
    full: true
    timeout: 500
  loop: "{{ range(0, vm.count) | list }}"

# TODO: could be usefult to wait until the vm appears in info
#- name: Wait until VM is ready
#  community.general.proxmox_vm_info:
#    api_user: '{{ api_user }}'
#    api_token_id: '{{ api_token_id }}'
#    api_token_secret: '{{ api_token_secret }}'
#    api_host: '{{ inventory_hostname }}'
#    node: '{{ vm.node }}'
#    name: '{{ vm.name }}'
#  register: vm_info
#  until: vm_info.proxmox_vms | length > 0
#  retries: 15
#  delay: 5

- name: Update VM parameters
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_host: "{{ inventory_hostname }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ node_base_vmid | int + item }}"
    memory: "{{ vm.memory }}"
    cores: "{{ vm.cores }}"
    ipconfig:
      ipconfig0: 'ip=dhcp'
    cicustom: 'user=local:snippets/{{ vm.name }}{{ node_base_vmid | int + item }}-user-data.yml'
    update: true
  loop: "{{ range(0, vm.count) | list }}"

- name: Resize VM
  community.general.proxmox_disk:
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_host: "{{ inventory_hostname }}"
    vmid: "{{ node_base_vmid | int + item }}"
    disk: "scsi0"
    size: "{{ vm.disk }}"
    state: "resized"
  loop: "{{ range(0, vm.count) | list }}"

- name: Start VM
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_token_id: "{{ api_token_id }}"
    api_token_secret: "{{ api_token_secret }}"
    api_host: "{{ inventory_hostname }}"
    vmid: "{{ node_base_vmid | int + item }}"
    state: "started"
  loop: "{{ range(0, vm.count) | list }}"